name: notes
description: "A new Flutter project by MR"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  args: ^2.5.0
  postgres: ^3.2.0
  postgresql2: any
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.4.5
  sqflite: ^2.3.3+1
  path: ^1.8.0
  intl: ^0.18.1
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  generate: true
